-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-02-14 11:57:36 CET
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



DROP TABLE autor CASCADE CONSTRAINTS;

DROP TABLE czytelnik CASCADE CONSTRAINTS;

DROP TABLE gatunek CASCADE CONSTRAINTS;

DROP TABLE ksiazka CASCADE CONSTRAINTS;

DROP TABLE narodowosc CASCADE CONSTRAINTS;

DROP TABLE wydawnictwo CASCADE CONSTRAINTS;

DROP TABLE wypozyczenia CASCADE CONSTRAINTS;
