-- Generated by Oracle SQL Developer Data Modeler 21.4.2.059.0838
--   at:        2022-08-25 17:35:05 CEST
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



DROP TABLE bd4_klient CASCADE CONSTRAINTS;

DROP TABLE bd4_produkt CASCADE CONSTRAINTS;

DROP TABLE bd4_rachunek CASCADE CONSTRAINTS;

DROP SEQUENCE seq_klient;

DROP SEQUENCE seq_produkt;

DROP SEQUENCE seq_rachunek;
